<?php
/*
 * Copyright (C) 2017 Anders Lövgren (Nowise Systems/BMC-IT, Uppsala University).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

?>

<script src="editor/plugins/ckeditor/ckeditor.js" type="text/javascript"></script>

<div id="editor-inline"></div>

<script>
        // 
        // The inline editor object.
        // 
        var inline_editor = (function () {
            var editor;

            return {
                open: function (source, mime) {
                    var config = {};
                    CKEDITOR.config.protectedSource.push(/<\?[\s\S]*?\?>/g);    // Protect PHP code
                    editor = CKEDITOR.appendTo('editor-inline', config, source);
                },
                close: function () {
                    editor.destroy();
                    editor = null;
                },
                value: function () {
                    return editor.getData();
                },
                show: function () {
                    document.getElementById('editor-inline').style.display = "block";
                },
                gettype: function () {
                    return 'inline';
                }
            };
        }());
</script>
