<?php
/*
 * Copyright (C) 2017 Anders Lövgren (Nowise Systems/BMC-IT, Uppsala University).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

?>

<link rel="stylesheet" href="editor/plugins/codemirror/lib/codemirror.css">

<script src="editor/plugins/codemirror/lib/codemirror.js"></script>

<script src="editor/plugins/codemirror/mode/xml/xml.js"></script>
<script src="editor/plugins/codemirror/mode/clike/clike.js"></script>

<script src="editor/plugins/codemirror/mode/htmlmixed/htmlmixed.js"></script>
<script src="editor/plugins/codemirror/mode/javascript/javascript.js"></script>
<script src="editor/plugins/codemirror/mode/php/php.js"></script>
<script src="editor/plugins/codemirror/mode/css/css.js" type="text/javascript"></script>

<script src="editor/plugins/codemirror/mode/shell/shell.js"></script>
<script src="editor/plugins/codemirror/mode/python/python.js" type="text/javascript"></script>

<script src="editor/plugins/codemirror/addon/display/autorefresh.js"></script>

<style>
    .CodeMirror { 
        z-index: 0;
        border: 1px solid #eee;
        height: 80%;
    }
</style>

<div id="editor-source">
</div>
<div class="w3-container w3-light-gray w3-padding-top">
    <input type="checkbox" onchange="source_editor.linewrap(this.checked)"><?= _("Toggle linewrap mode") ?> 
    <input type="checkbox" onchange="source_editor.linenums(this.checked)" checked=""><?= _("Show line numbers") ?>
</div>

<script>
        // 
        // The source editor object.
        // 
        var source_editor = (function () {
            var editor = null, target = document.getElementById('editor-source');

            function config() {
                CodeMirror.defineMIME('text/x-shellscript', 'shell');
            }

            function create() {
                editor = CodeMirror(target, {
                    lineNumbers: true,
                    matchBrackets: true,
                    autoRefresh: true,
                    indentUnit: 8,
                    indentWithTabs: false
                });
            }

            function instance() {
                if (editor === null) {
                    config();
                    create();
                }
                return editor;
            }

            return {
                open: function (source, mime) {
                    editor = instance();
                    editor.setOption("mode", mime);
                    editor.setValue(source);
                },
                close: function () {
                    target.removeChild(editor.getWrapperElement());
                    editor = null;
                },
                value: function () {
                    return editor.getValue();
                },
                show: function () {
                    target.style.display = "block";
                },
                gettype: function () {
                    return 'source';
                },
                linewrap: function (enable) {
                    editor.setOption("lineWrapping", enable);
                },
                linenums: function (enable) {
                    editor.setOption("lineNumbers", enable);
                }
            };
        }());
</script>
