<?php
/*
 * Copyright (C) 2017 Anders Lövgren (QNET/BMC CompDept).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

?>

<style>
    #context-menu {
        position: relative;
        float: right;
    }
</style>

<div id="content-context w3-right">
    <div id="context-menu" class="w3-dropdown-hover">
        <button class="w3-button w3-light-grey"><i class="fa fa-plus-square-o" aria-hidden="true" ></i> Create </button>
        <div class="w3-dropdown-content w3-bar-block w3-card-4">
            <a href="#" class="w3-bar-item w3-button" onclick="create_context('content')"><?= _("Content Specification") ?></a>
            <a href="#" class="w3-bar-item w3-button" onclick="create_context('publish')"><?= _("Publisher Information") ?></a>
            <a href="#" class="w3-bar-item w3-button" onclick="create_context('headers')"><?= _("Custom Headers") ?></a>
        </div>        
    </div>

    <h1><?= _("Context") ?></h1>
    <div id="context-listing"></div>
</div>

<script>
        /**
         * Create file from template and reload table.
         * @param {String} source The template source.
         */
        function create_context(source) {
            var templates = {
                content: 'content.spec',
                headers: 'headers.inc',
                publish: 'publish.inc'
            };
            var target = templates[source];

            api.create(source, target, function (xhr) {
                var response = JSON.parse(xhr.responseText);
                if (response.status === 'success') {
                    load_content_section('context-listing', 'context');
                } else if (response.status === 'failure') {
                    alert(response.message);
                }
            });
        }
</script>
