<?php
/*
 * Copyright (C) 2017 Anders Lövgren (QNET/BMC CompDept).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

?>

<style>
    #menus-menu {
        position: relative;
        float: right;
    }
</style>

<div id="content-menus w3-right">
    <div id="menus-menu" class="w3-dropdown-hover">
        <button class="w3-button w3-light-grey"><i class="fa fa-plus-square-o" aria-hidden="true" ></i> Create </button>
        <div class="w3-dropdown-content w3-bar-block w3-card-4">
            <a href="#" class="w3-bar-item w3-button" onclick="create_menus('standard')"><?= _("Standard Menu") ?></a>
            <a href="#" class="w3-bar-item w3-button" onclick="create_menus('sidebar')"><?= _("Sidebar Menu") ?></a>
            <a href="#" class="w3-bar-item w3-button" onclick="create_menus('topbar')"><?= _("Topbar Menu") ?></a>
        </div>        
    </div>

    <h1><?= _("Context") ?></h1>
    <div id="menus-listing"></div>
</div>

<script>
        /**
         * Create file from template and reload table.
         * @param {String} source The template source.
         */
        function create_menus(source) {
            var templates = {
                standard: 'standard.menu',
                sidebar: 'sidebar.menu',
                topbar: 'topbar.menu'
            };
            var target = templates[source];

            api.create(source, target, function (xhr) {
                var response = JSON.parse(xhr.responseText);
                if (response.status === 'success') {
                    load_content_section('menus-listing', 'menus');
                } else if (response.status === 'failure') {
                    alert(response.message);
                }
            });
        }
</script>
