<?php
/*
 * Copyright (C) 2017 Anders Lövgren (QNET/BMC CompDept).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

?>

<p>
    <span><i class="fa fa-check" style="color: #33cc33"></i></span> 
    <?= sprintf(_("Logged on using %s"), $desc) ?>
</p>
<p>
    <span style="margin: 20px">
        <input type="button" style="min-width: 80px" class="w3-btn w3-red" onclick="window.location = '<?= $this->config->url($this->config->auth['logoff']) ?>'" value="<?= _("Logoff") ?>">
        <input type="button" style="min-width: 80px" class="w3-btn w3-indigo" onclick="window.history.back()" value="<?= _("Back") ?>">
    </span>
</p>

<span><i class="fa fa-info-circle" style="color: #3366ff"></i></span>
<?= _("Session details:") ?>
<div style="margin: 20px">
    <?= sprintf(_("Logged on as %s from %s (%s)"), $this->session->user, gethostbyaddr($this->session->peer), $this->session->peer) ?>
    <br>
    <?= sprintf(_("Expires %s"), strftime("%x %X", $this->session->expires)) ?>
    <br>
    <?= sprintf(_("Renew at %s"), strftime("%x %X", $this->session->refresh)) ?>
</div>    
