<?php
/*
 * Copyright (C) 2017 Anders Lövgren (QNET/BMC CompDept).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

?>

<div>
    <div id="auth-login">
        <select id="auth-select" onchange="auth_description()">
            <?php foreach ($this->auth->authenticators(true) as $name => $auth) : ?>
                    <option value="<?= $name ?>" desc="<?= $auth->description ?>">
                        <?= $auth->name ?>
                    </option>
            <?php endforeach; ?>
        </select>
        <input type="button" class="w3-btn w3-green" style="min-width: 100px" onclick="auth_selected()" value="<?= _("Continue") ?>" >
        <div id="auth-method-descr"></div>
    </div>
</div>

<script>
        function auth_description()
        {
            var select = document.getElementById('auth-select');
            var option = select.options[select.selectedIndex];

            document.getElementById('auth-method-descr').innerHTML = option.attributes['desc'].value;
        }

        function auth_selected()
        {
            var select = document.getElementById('auth-select');
            var option = select.options[select.selectedIndex];
            var target = '?auth=' + option.value + '&ajax=1';

            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState === 4 && this.status === 200) {
                    document.getElementById("auth-login").innerHTML = this.responseText;
                }
            };
            xhttp.open("GET", target, true);
            xhttp.send();
        }

        document.onreadystatechange = function () {
            if (document.readyState === 'complete') {
                auth_description();
            }
        }

</script>
