<?php
/*
 * Copyright (C) 2017 Anders Lövgren (QNET/BMC CompDept).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

?>

<p>
    <?= _("Choose logon method by clicking one of the buttons:") ?>
</p>

<?php foreach ($this->auth->authenticators(true) as $name => $auth) : ?>
        <div style="padding: 10px">
            <input type="button" class="w3-btn w3-green" value="<?= $auth->name ?>" style="min-width: 100px" onclick="window.location = '?auth=<?= $name ?>'">
            <span style="margin-left: 20px"><?= $auth->description ?></span>
        </div>
<?php endforeach; ?>
