<?php
/*
 * Copyright (C) 2017 Anders Lövgren (QNET/BMC CompDept).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// 
// File content editor.
// 

?>

<div class="editor" style="display: none">
    <h1>Editor</h1>
    <div class="w3-container w3-margin-top">
        <div class="w3-bar">
            <button class="w3-bar-item w3-btn tablink" onclick="open_inline_editor(event)"><?= _("Inline") ?></button>
            <button class="w3-bar-item w3-btn tablink" onclick="open_source_editor(event)"><?= _("Source") ?></button>
            <button class="w3-bar-item w3-btn tablink" onclick="open_default_editor(event)"><?= _("Default") ?></button>
        </div>

        <div id="inline" class="w3-container editor-section" style="display:none">
            <?php require_once('inline.phtml'); ?>
        </div>

        <div id="source" class="w3-container editor-section" style="display:none">
            <?php require_once('source.phtml'); ?>
        </div>
        
        <div id="default" class="w3-container editor-section" style="display:none">
            <?php require_once('default.phtml'); ?>
        </div>
    </div>
</div>

<script>
        function open_editor_section(evt, sect) {
            var i, x, tablinks;
            x = document.getElementsByClassName("editor-section");
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablink");
            for (i = 0; i < x.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" w3-red", "");
            }
            document.getElementById(sect).style.display = "block";
            evt.currentTarget.className += " w3-red";
        }

        function open_editor(file) {

        }

</script>
