<?php
/*
 * Copyright (C) 2017 Anders Lövgren (QNET/BMC CompDept).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

?>

<div id="editor-inline">
</div>

<script>
        // 
        // The inline editor object.
        // 
        var inline_editor = (function () {
            var editor;

            return {
                open: function (source, mime) {
                    console.log("inline_editor->open(" + mime + ")");
                },
                close: function () {
                    console.log("inline_editor->close()");
                },
                value: function () {
                    console.log("inline_editor->value()");
                },
                show: function () {
                    console.log("inline_editor->show()");
                    document.getElementById('editor-inline').style.display = "block";
                },
                gettype: function() {
                        return 'inline';
                }
            };
        }());
</script>
