<div class="w3-panel w3-light-gray">
    <h3>Simple View</h3>
    <p>
        This content has been created from a simple view. The dispatch router has wrapped the
        content in a view class. Using simple views is a great options when developing a web
        site as you can focus primarly on the content.
    </p>
    <p>
        Views are not intended for web applications, but because of the dispatch routing you 
        can access injected services thru the $this pointer from your view page.
    </p>
    <?php include("details.inc") ?>
</div>
