<?php

return array(
        'meta' => array(
                array(
                        'name'    => 'description',
                        'content' => 'Site and application template system'
                ),
                array(
                        'name'    => 'author',
                        'content' => 'Anders Lövgren'
                ),
                array(
                        'name'    => 'keywords',
                        'content' => 'php,template,router'
                ),
                array(
                        'http-equiv' => 'Content-Type',
                        'content'    => 'text/html;charset=utf-8'
                )
        )
);
