<?php

return array(
        "contact" => array(
                "href" => "http://directory.example.com/info/?id=4775",
                "name" => _("Page Responsible")
        ),
        "editor"  => array(
                "href" => "http://www.example.com/webmaster",
                "name" => _("Webmaster")
        ),
        "copying" => sprintf("2015-%s", date('Y')),
        "updated" => getlastmod()
);
