<?php
/*
 * Copyright (C) 2017 Anders Lövgren (QNET/BMC CompDept).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

?>

<span><i class="fa fa-check" style="color: #33cc33; min-width: 20px"></i></span> 
<?= ("Your logon session has been destroyed.") ?>

<?php if ($auth) : ?>
        <br>
        <span><i class="fa fa-info-circle" style="color: #3366ff; min-width: 20px"></i></span> <?= sprintf(_("You are still logged on to %s:"), $desc) ?>
        <p>
            <span style="margin: 20px">
                <input type="button" class="w3-btn w3-blue" onclick="window.location = '?auth=<?= $name ?>'" value="<?= sprintf(_("Logout from %s"), $auth->name) ?>">
            </span>
        </p>
<?php else: ?>
        <p>
            <span style="margin: 20px">
                <input type="button" class="w3-btn w3-blue" onclick="window.location = '<?= $this->config->url($this->config->auth['logon']) ?>'" value="<?= _("Logon") ?>">
            </span>
        </p>
<?php endif; ?>
