<?php
/*
 * Copyright (C) 2017 Anders Lövgren (QNET/BMC CompDept).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

?>

<div id="edit-area">
    <?php require_once('navigator.phtml') ?>
    <?php require_once('content/index.phtml') ?>
    <?php require_once('editor/index.phtml') ?>
</div>

<script>
//        function open_section(name) {
//                if(name == 'content') {
//                        open_files_section();
//                } else {
//                        open_editor_section()
//                }
//        }

        document.getElementById("edit-area").addEventListener('DOMContentLoaded', function () {
            console.log("HERE");
            open_files_content();
        }, false);
//        document.onload = function() {
//                console.log("HERE");
//                open_files_content();
//        }
</script>
