<div class="w3-panel w3-container w3-light-gray">
    <h3>Standard Page</h3>
    <p>
        This content has been created from a class deriving from the standard page class. 
        Using controller classes is preferable when developing web applications as you then
        have access to request parameters, context and authentication when deciding which 
        view to load.
    </p>
    <p>
        In addition to standard controller and views, there's also classes for secure 
        pages (enforcing authentication) and web services (no template rendering).
    </p>
    <?php include(__DIR__ . "/../details.inc") ?>
</div>
