<?php
/*
 * Copyright (C) 2017 Anders Lövgren (Nowise Systems/BMC-IT, Uppsala University).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

?>

<p>
    <?= sprintf(_("Logon using %s:"), $desc) ?>
</p>
<div style="padding-left: 15px">
    <form action="?auth=<?= $form ?>" method="POST">
        <p>
            <label for="fuser"><?= _("Username:") ?></label>
            <input type="text" id="user" name="<?= $auth->fuser ?>" placeholder="user@example.com">
        </p>
        <p>
            <label for="fpass"><?= _("Password:") ?></label>
            <input type="password" id="pass" name="<?= $auth->fpass ?>" placeholder="<?= _("Type your password") ?>">
        </p>
        <p>
            <input type="checkbox" id="toggle-pass" onclick="toggle_show_password('pass')"> <?= _("Show password") ?>
        </p>
        <p>
            <input type="button" value="<?= _("Back") ?>"  class="w3-btn w3-blue" onclick="window.history.back()">            
            <input type="submit" value="<?= _("Login") ?>" class="w3-btn w3-green" name="<?= $auth->fname ?>">            
        </p>
    </form>
</div>

<script>
        function toggle_show_password(name) {
            var elem = document.getElementById(name);
            if (elem.attributes['type'].value === 'text') {
                elem.attributes['type'].value = 'password';
            } else {
                elem.attributes['type'].value = 'text';
            }
        }
</script>
