<?php
/*
 * Copyright (C) 2017 Anders Lövgren (QNET/BMC CompDept).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

?>

<script id="runscript">
        var selected_auth = false;

        // 
        // Show description for authenticator.
        // 
        function auth_description(link)
        {
            if (!selected_auth) {
                document.getElementById('auth-method-desc').innerHTML = link.attributes['desc'].value;
            }
        }

        // 
        // Select authenticator.
        // 
        function auth_selected(link)
        {
            if (link) {
                document.getElementById('auth-method-name').innerHTML = link.innerHTML;
                document.getElementById('auth-method-desc').innerHTML = link.attributes['desc'].value;
                selected_auth = link.attributes['name'].value;
            }
        }

        // 
        // Continue logon using selected authenticator.
        // 
        function auth_continue()
        {
            if (!selected_auth) {
                return false;
            }

            var logon = "<?= $this->config->url($this->config->auth['logon']) ?>"
            window.location = logon + '?auth=' + selected_auth;
        }

</script>

<div>
    <div id="auth-login">
        <div id="auth-method-desc" style="padding-bottom: 5px"><?= _("Select authentication method:") ?></div>
        <div class="w3-dropdown-hover">
            <button id="auth-method-name" class="w3-btn" style="min-width: 100px">Select</button>
            <div id="auth-method-select" class="w3-dropdown-content w3-white w3-card-4 w3-animate-zoom">
                <?php foreach ($this->auth->authenticators(true) as $name => $auth) : ?>
                        <a href="#" 
                           class="auth-method"
                           name="<?= $name ?>"
                           desc="<?= $auth->description ?>"
                           onmouseover="auth_description(this)"
                           onclick="auth_selected(this)"
                           >
                               <?= $auth->name ?>
                        </a>
                <?php endforeach; ?>
            </div>
        </div>
        <input type="button" class="w3-btn w3-green" style="min-width: 100px" onclick="auth_continue()" value="<?= _("Continue") ?>" >
    </div>
</div>
